### ISSUE TITLE
Is this available under BSD license or just GPL???

### ISSUE THREAD

**Issue by Sonophoto** [OLIMEX/olimex-iot-firmware-esp8266#1]
This is your development tools for your hardware product? Right?

**Comment by TsvetanUsunov** [comment]
Hi
there is license file in the project repo:
https://github.com/OLIMEX/olimex-iot-firmware-esp8266/blob/master/LICENSE
Thanks

**Comment by Sonophoto** [comment]
Hi Tsvetan,

One of our engineers found your products on Digikey and was quite excited about it for an IoT project. When we looked at the software for it everything was GPL licensed in such a way that LINKING with your software INFECTS our code with your choice of LICENSE. We didn't even bother asking the lawyers.

If you insist on using GPL you may wish to consider using LGPL because I GUARANTEE you that GPL is silently costing you sales of your hardware - Because almost no one will bother telling you...

**Comment by TsvetanUsunov** [comment]
Sorry, the license is and will stay GPL

**Comment by Sonophoto** [comment]
That's fine, and we wont now or in the future use your products. Good job.
